# Base namespace for all generated files
namespace = "InternetClients"

# Will create a subfolder within this directory with all the files
output-directory = "Growtown/Assets/Scripts/ICP_CONNECT/Api"

# Will override default boundary node url (like for local development)
# Only useful for generating clients from a canister id
#url = "https://localhost:8000"

# Will make generated files in a flat structure with no folders, for all clients
#no-folders = true

#override-optional-value = true

[[clients]]
# Defines name folder and api client class name
name = "greetBackendCanister"

# Get definition from a *.did file
type = "file"

# Path to the *.did file to use
file-path = "src/declarations/Growntown_Backend/Growntown_Backend.did"

# Will make generated files in a flat structure with no folders, for this client
#no-folders = true

[[clients]]
# Defines name folder and api client class name
name = "icrc2TokenCanister"

# Get definition from a *.did file
type = "file"

# Path to the *.did file to use
file-path = "src/declarations/icrc2_token_canister/icrc2_token_canister.did"

# Will make generated files in a flat structure with no folders, for this client
#no-folders = true